### Import necessary libraries

- Import necessary libraries: networkx, matplotlib.pyplot, numpy, seaborn, and pyvis.network.

In [29]:
import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from pyvis.network import Network

### Optional function to get an interactive graph

In [30]:
def make_interacting_graph(G : nx.graph):
    g = Network(height=800, width=800, notebook=True, cdn_resources='remote', directed =True)
    g.barnes_hut()
    
    # Add nodes to the network
    for node in G.nodes:
        node_name = str(node)  # Convert node to string if it's not already
        g.add_node(node, label=node_name, size=50, title=node_name, font={'size' : 50})
    
    # Add edges to the network
    for edge in G.edges:
        src, dst, action, reward = edge[0], edge[1], G.edges[edge]['action'], G.edges[edge]['reward']
        g.add_edge(src, dst, label=f"Action : {action} \n Reward : {reward}", font={'size': 50})

    return g

### Define here: States, reward and transition probability matrix

- Define the states and rewards for each state.
- Define the transition probabilities between states.


In [31]:
# Define the states
states = ['subject1', 'subject2','subject3','pass','instagram','bar','sleep']

# Define the rewards for each state
rewards = {
    'subject1': {-2},
    'subject2': {-2},
    'subject3': {-2},
    'pass': {10},
    'instagram': {-1},
    'bar': {1},
    'sleep': {0},
}

# Define the transition probabilities explicitly
transition_probs = {
    ('instagram', 'instagram'): 0.9,
    ('instagram', 'subject1'): 0.1,
    ('subject1', 'subject2'): 0.5,
    ('subject1', 'instagram'): 0.5,
    ('subject2', 'sleep'): 0.2,
    ('subject2', 'subject3'): 0.8,
    ('subject3', 'pass'): 0.6,
    ('subject3', 'bar'): 0.4,
    ('bar', 'subject1'): 0.2,
    ('bar', 'subject2'): 0.4,
    ('bar', 'subject3'): 0.4,
    ('pass', 'sleep'): 1,
}

## Use seaborn to plot the transition probability matrix

### Expected Output
 - Compute the transition matrix based on the defined transition probabilities
 - Plot the transition matrix using seaborn.heatmap()

![alt text](Transition_prob_matrix.png "Title")


In [91]:
# Define the state transition probabilities
#...
data = np.zeros((7,7))
print(data)

col1 = []
col2 = []
my_dict = {}

for i, e in enumerate(states):
    my_dict[i] = e

print(my_dict)

print(type(transition_probs))
#print(transition_probs[list(transition_probs.keys())[0]])
#print(transition_probs[list(transition_probs.values())[0]])
print("Keys:", list(transition_probs.keys()))

print(tuple(k) for k in transition_probs.values())

# Print values
print("Values:", (list(transition_probs.values())))
 
# Print both keys and values
print("Keys and Values:")
print(transition_probs)

for value,key in transition_probs.items():
    col1.append(value[0])
    col2.append(value[1])

print(col1)
print(col2)
# Assign transition probabilities based on the defined transitions
#...
for index in transition_probs:
    for a in range (0,7):
        if index[0] == col1[a]:
            print("a:",col1[a])
            for b in range (0,7):
                if index[1] == col2[b]:
                    data[a][b] = 2
                    print("Putting 2 in [",a,"][",b,"]")

print(data)
# Plot the transition matrix


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
{0: 'subject1', 1: 'subject2', 2: 'subject3', 3: 'pass', 4: 'instagram', 5: 'bar', 6: 'sleep'}
<class 'dict'>
Keys: [('instagram', 'instagram'), ('instagram', 'subject1'), ('subject1', 'subject2'), ('subject1', 'instagram'), ('subject2', 'sleep'), ('subject2', 'subject3'), ('subject3', 'pass'), ('subject3', 'bar'), ('bar', 'subject1'), ('bar', 'subject2'), ('bar', 'subject3'), ('pass', 'sleep')]
<generator object <genexpr> at 0x7f78c9a7d660>
Values: [0.9, 0.1, 0.5, 0.5, 0.2, 0.8, 0.6, 0.4, 0.2, 0.4, 0.4, 1]
Keys and Values:
{('instagram', 'instagram'): 0.9, ('instagram', 'subject1'): 0.1, ('subject1', 'subject2'): 0.5, ('subject1', 'instagram'): 0.5, ('subject2', 'sleep'): 0.2, ('subject2', 'subject3'): 0.8, ('subject3', 'pass'): 0.6, ('subject3', 'bar'): 0.4, ('bar', 'subject1'): 0.2, ('bar', 'subject2'): 0.4, ('bar', 

## Building the graph

- Create a directed graph using nx.DiGraph().
- Add nodes to the graph for each state.
- Add edges to represent transitions between states, including associated actions and rewards.

### Expected Output
![alt text](Graph.png "Title")



In [27]:
# Create a directed graph
G = nx.DiGraph()

# Add nodes and edges to the graph


# Draw the graph
plt.figure(figsize=(12, 8))
pos = nx.spring_layout(G, seed=42)  # Define layout for visualization
#Hint: See networkx draw and draw_networkx_edge_lables_documentation
plt.show()


make_interacting_graph(G).show("graph.html")

<Figure size 1200x800 with 0 Axes>

graph.html


## Computing Value Functions:
 - Define the discount factor.
 - Use the Bellman equation to compute the value function of each state.


In [22]:
identity = np.eye(len(transition_matrix))
discount_factor = 0
V = np.matmul()

NameError: name 'transition_matrix' is not defined

## Visualizing the Graph with Value Functions:
- Draw the graph using nx.draw() with appropriate node positions
- Annotate each node with its corresponding value function
- Annotate each edge with associated actions and rewards

### Expected Output

![alt text](Value_graph.png "Title")

In [ ]:
# Draw the graph with value functions annotated inside nodes
plt.figure(figsize=(12, 8))
pos = nx.planar_layout(G)  # Define layout for visualization


# Create node labels with formatted value functions

# Draw node labels
G = nx.relabel_nodes(G, node_labels)

# Draw edge labels

plt.show()

make_interacting_graph(G).show("value_graph.html")

### Visualizing Value Function Dynamics:
- Use matplotlib to visualize how the value function changes with different discount factors.

### Expected Output
![alt text](Discount_variation.png "Title")


In [ ]:
# Computing value functions with different discount factors
discount_factors = [0, 0.1, 0.2, 0.3,0.4, 0.5, 0.6, 0.7, 0.8, 0.9]  # Set different discount factors to test
for discount_factor in discount_factors:

    
    # Store the value functions for analysis
    

# Plotting value functions against discount factors
plt.show()